import { GoogleGenAI, Modality, Part } from "@google/genai";

// Ensure the API key is available from environment variables
if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const createPrompt = (description: string): string => {
  return `
You are an expert YouTube thumbnail designer for a high-tech AI channel called "ImbilaAI".
Your task is to generate a single, compelling, viral-ready thumbnail image based on a video description.

**Video Description:**
"${description}"

**CRITICAL GUIDELINES (MUST FOLLOW):**

1.  **Resolution & Aspect Ratio:** The image MUST be 1280x720 pixels (16:9 aspect ratio).
2.  **Visual Style:**
    *   **Theme:** Futuristic, high-tech, digital, abstract, and AI-centric.
    *   **Color Palette:** Use a dark background (deep space black, dark blues, purples). Contrast this with vibrant, glowing neon elements in colors like electric cyan, magenta, and bright purple. The overall mood should be professional, intriguing, and modern.
    *   **Composition:** Create a visually stunning and clear focal point. It should be eye-catching and immediately understandable, even at small sizes. Use dynamic compositions, interesting angles, and a sense of depth.
3.  **Content Rules:**
    *   **Clarity:** The thumbnail must be high-quality, clear, and easy to understand at a glance. Avoid clutter.
    *   **Boldness:** Use high contrast and bold visuals to stand out.
    *   **NO TEXT:** Do NOT add any text overlays to the image. The visuals alone should convey the topic.
    *   **NO LOGOS:** Do NOT include any YouTube logos, play buttons, or any other brand logos.
    *   **Originality:** The image must be completely original and not violate any copyrights.
    *   **Relevance:** The image must accurately and compellingly represent the core topic from the video description.

**Goal:** Create a cinematic, visually arresting image that makes a viewer curious and eager to click, perfectly matching the "ImbilaAI" channel's high-tech aesthetic.
`;
};

export const generateThumbnail = async (description: string): Promise<string> => {
  const prompt = createPrompt(description);

  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '16:9',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No images were generated by the API.");
    }
  } catch (error) {
    console.error("Error calling Gemini API for generation:", error);
    throw new Error("Failed to generate thumbnail from the API.");
  }
};

const createEnhancePrompt = (title: string, hasLogo: boolean): string => {
  let prompt = `
You are an expert graphic designer specializing in YouTube thumbnails for a high-tech AI channel.
Your task is to expertly add a text title and, if provided, a logo to the given thumbnail image. The first image is the base thumbnail. The second image, if it exists, is the logo.

**CRITICAL INSTRUCTIONS (MUST FOLLOW):**

1.  **Add Title:** Overlay the following text onto the image: "${title}".
    *   **Font & Style:** Use a bold, futuristic, sans-serif font that complements the high-tech aesthetic of the image. The text MUST be crystal clear and easily readable on all screen sizes.
    *   **Color & Effect:** The text color should be a bright, high-contrast color, such as white or a vibrant neon color (like cyan or magenta) drawn from the image's own palette. To ensure maximum legibility, apply a subtle, dark drop shadow or a soft outer glow that matches the lighting in the image. The goal is to make the text pop while looking integrated.
    *   **Placement:** Strategically place the title in the **lower third** of the image, preferably in an area with less visual clutter like the bottom-left. It MUST NOT obscure the central subject of the image.
    *   **Size:** The title should be prominent and impactful but should not dominate the visual. It should occupy roughly 15-25% of the image width.

2.  **Image Integrity:** You MUST NOT change the background image in any way. Do not alter its colors, composition, or style. Your only job is to overlay the text and logo.
`;

  if (hasLogo) {
    prompt += `
3.  **Add Logo:** The second image provided is the logo. You MUST place this logo in the **bottom-right corner**.
    *   **Placement:** It must be placed precisely in the bottom-right corner, with a small, consistent margin from the edges.
    *   **Size:** The logo must be small and unobtrusive. Scale it down to approximately 5-8% of the thumbnail's total width.
`;
  }

  prompt += `
**Final Output:** Your final output MUST be only the modified 1280x720 JPEG image. Do not add any extra text, descriptions, or explanations. Just the final image.
`;
  return prompt;
};

export const enhanceThumbnail = async (
  base64ImageData: string,
  title: string,
  logo: { B64: string, mimeType: string } | null
): Promise<string> => {

    const parts: Part[] = [
        {
            inlineData: {
                mimeType: 'image/jpeg',
                data: base64ImageData,
            },
        },
        // The prompt must come *after* the base image.
    ];

    if (logo) {
        parts.push({
             inlineData: {
                mimeType: logo.mimeType,
                // FIX: Corrected a typo in the property name from `logo.B4` to `logo.B64`.
                data: logo.B64,
            },
        })
    }

    // Add the text prompt as the last part.
    parts.push({ text: createEnhancePrompt(title, !!logo) });


    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: { parts },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        const imagePart = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
        if (imagePart && imagePart.inlineData) {
            const base64ImageBytes: string = imagePart.inlineData.data;
            const mimeType = imagePart.inlineData.mimeType;
            return `data:${mimeType};base64,${base64ImageBytes}`;
        } else {
            throw new Error("No enhanced image was returned by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API for enhancement:", error);
        throw new Error("Failed to enhance thumbnail from the API.");
    }
};
